import React from "react";

/**
 * AnalyticalTab
 * Shows all analytical pumping test fits:
 *  - Theis curve match
 *  - Cooper-Jacob straight-line
 *  - Neuman delayed-yield
 *  - Pumping well + observation well drawdown
 *
 * results must contain:
 *   results.plots = {
 *      theis_plot: "data:image/png;base64,...",
 *      cooper_plot: "...",
 *      neuman_plot: "...",
 *      drawdown_plot: "..."
 *   }
 */

export default function AnalyticalTab({ results }) {
  if (!results) return <p>No analytical results available.</p>;

  const plots = results.plots || {};

  return (
    <div style={{ paddingBottom: "40px" }}>
      <h2 style={{ marginTop: 0 }}>Analytical Model Fits</h2>
      <p>
        These plots show the analytical solutions compared to the observed
        drawdown values. They are generated by the backend using matplotlib and
        embedded as base64 PNG images.
      </p>

      {/* ---- DRAWNDOWN SCATTER ---- */}
      <Section title="Observed Drawdown (Field Data)">
        <ImageOrPlaceholder src={plots.drawdown_plot} />
      </Section>

      {/* ---- THEIS ---- */}
      <Section title="Theis Curve Match (Non-Equilibrium Solution)">
        <ImageOrPlaceholder src={plots.theis_plot} />
        <p style={noteStyle}>
          The Theis solution uses the exponential integral well function W(u)
          and is most appropriate for confined aquifers or early-time behavior.
        </p>
      </Section>

      {/* ---- COOPER-JACOB ---- */}
      <Section title="Cooper-Jacob Straight-Line Method">
        <ImageOrPlaceholder src={plots.cooper_plot} />
        <p style={noteStyle}>
          The Cooper-Jacob approximation linearizes the Theis solution for late-time
          drawdown where u = r²S / (4Tt) &lt; 0.01. It is widely used for regulatory
          determinations due to its stability.
        </p>
      </Section>

      {/* ---- NEUMAN ---- */}
      <Section title="Neuman Delayed-Yield Fit (Unconfined Aquifer)">
        <ImageOrPlaceholder src={plots.neuman_plot} />
        <p style={noteStyle}>
          The Neuman model accounts for elastic storage plus delayed gravity
          drainage, making it appropriate for unconfined aquifers and aquifers
          with partial penetration.
        </p>
      </Section>
    </div>
  );
}

/* --------------------
   Section Wrapper
-------------------- */
function Section({ title, children }) {
  return (
    <div style={{ marginBottom: "35px" }}>
      <h3 style={{ marginBottom: "10px" }}>{title}</h3>
      {children}
    </div>
  );
}

/* ----------------------------
   Image Display or Placeholder
----------------------------- */
function ImageOrPlaceholder({ src }) {
  if (!src) {
    return (
      <div style={placeholderStyle}>
        <em>No plot available.</em>
      </div>
    );
  }

  return (
    <img
      src={src}
      alt="Analytical Plot"
      style={{
        width: "100%",
        maxHeight: "420px",
        objectFit: "contain",
        border: "1px solid #ccc",
        borderRadius: "6px",
        background: "white"
      }}
    />
  );
}

/* ---- Styles ---- */

const placeholderStyle = {
  width: "100%",
  height: "250px",
  background: "#efefef",
  borderRadius: "6px",
  border: "1px solid #ccc",
  display: "flex",
  alignItems: "center",
  justifyContent: "center",
  color: "#777",
  fontStyle: "italic"
};

const noteStyle = {
  fontSize: "12px",
  color: "#666",
  marginTop: "8px"
};
